name: eco_bin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.5.0
  flame_noise: ^0.3.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flame_audio: ^2.10.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Crunch Chips
      fonts:
        - asset: assets/fonts/Crunch Chips.otf


  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
